Feature/bngp 527 cya
DEFRA/biodiversity-net-gain-service pull request #191
Opened 2022-10-27 12:43 UTC by reneli5

2022-11-08 13:53 UTC, pwadmore-ea requested changes
@reneli5 - I've raised a number of comments but I don't think there is anything major.

- In addition to the comments on individual changes please check the general formatting of packages/webapp/src/views/land/register-land-task-list.html.
- **Observed defect using branch code** - No details shown on check land boundary details page (observed in Chrome and Firefox) 
![image](https://user-images.githubusercontent.com/8915039/200581508-ab7b69d2-f744-492e-9eb1-5dcfbd4f1df5.png)
- I suggest making the upload pages neater if they are accessed out of of sequence
![image](https://user-images.githubusercontent.com/8915039/200582242-55bb4fbb-a959-4130-a607-5e8d1115097b.png)

2022-11-08 13:53 UTC, pwadmore-ea commented on packages/webapp/src/routes/land/check-ownership-details.js
> +function getOwneershipFileName (fileLocation) {
Typo - ownership

2022-11-10 08:30 UTC, reneli5 commented on packages/webapp/src/routes/__tests__/land/register-land-task-list.spec.js
> +      expect(contextResult.registrationTasks.taskList.length).toEqual(5)
That is managed by the application, it is much of a completion step.

2022-11-10 08:33 UTC, reneli5 commented on packages/webapp/src/routes/__tests__/land/check-legal-agreement-details.spec.js
> +  it('should continue with the flow with other party role name', done => {
Refactored

2022-11-10 10:37 UTC, reneli5 commented on packages/webapp/src/routes/land/check-geospatial-land-boundary-file.js
> +        route = constants.routes.CHECK_LAND_BOUNDARY_DETAILS
This flow need to be covered by this ticket: https://eaflood.atlassian.net/browse/BNGP-526

2022-11-10 10:46 UTC, reneli5 commented on packages/webapp/src/routes/land/landowner-consent.js
> +    if (!consent) {
landownerConsent will either be true or undefined. Don't see any need for parsing it.

2022-11-10 11:13 UTC, reneli5 commented on packages/webapp/src/routes/land/legal-agreement-type.js
> +    if (legalAgreementType !== undefined) {
Not needed. I have reverted it.

2022-11-10 13:54 UTC, pwadmore-ea approved these changes
Unable to reproduce blank land boundary check your details locally again. If I can reproduce it at some point it can be investigated then.

2022-11-10 13:55 UTC, merged