initial database scripts for application reference generation
DEFRA/biodiversity-net-gain-service pull request #215
Opened 2023-01-04 16:21 UTC by teddmason

2023-01-16 14:42 UTC, teddmason commented
This PR includes changes made on https://github.com/DEFRA/biodiversity-net-gain-service/pull/218

2023-01-16 17:24 UTC, teddmason commented
@pwadmore-ea I can take you through the logic for this at some point.  Key risks that i thought of that I'm hoping the work addresses are as follows:

- Generating a duplicate reference number for multiple users submitting at the same time
- reference ordering and counting correctly when we clock change to BST

2023-01-24 17:38 UTC, pwadmore-ea requested changes

2023-01-25 07:36 UTC, teddmason commented on packages/database-version-control/src/migrations/2023.01.04T10.57.15.create-bng-schema.sql
> +     CREATE SCHEMA bng;
I'd rather not, as it wraps the USAGE and PRIVALEDGE statements too

2023-01-25 07:53 UTC, teddmason commented on packages/database-version-control/src/migrations/2023.01.04T15.26.58.create-application-reference-function.sql
> +create function bng.fn_create_application_reference()
CREATE FUNCTION IF NOT EXISTS is not valid.  Only option would be to have a drop function before the create.  But I see the need for the IF exists on the source control to be minor. If the NOT EXISTS checks are required then something has gone wrong with the database setup, and potentially having the NOT EXISTS checks could hide that

2023-01-25 09:09 UTC, pwadmore-ea commented
> @pwadmore-ea I can take you through the logic for this at some point. Key risks that i thought of that I'm hoping the work addresses are as follows:
> 
>     * Generating a duplicate reference number for multiple users submitting at the same time
> 
>     * reference ordering and counting correctly when we clock change to BST

@teddmason - Hopefully this comment reflects what we have discussed outside GitHub:

- Addition of a unique constraint on the application_reference column of the database table to guard against allocation of duplicate references.
- Use of timestamp with timezone column on the database table with UTC as the time zone so no local times are stored in the database. I acknowledge that this means some allocations during BST are at risk of being assigned to the wrong day. If this causes issues, potential solutions can be investigated accordingly.

2023-01-25 12:39 UTC, pwadmore-ea approved these changes

2023-01-25 12:56 UTC, merged