first commit
DEFRA/biodiversity-net-gain-service pull request #219
Opened 2023-01-18 13:29 UTC by teddmason

2023-01-30 13:48 UTC, pwadmore-ea requested changes
In addition to file specific comments I am wondering if:

- gain-site-reference needs renaming to application-reference.
- gainSiteReference needs renaming to applicationReference.

Based on service level communications I believe
- an application reference number is associated with journey data submitted for operator validation.
- a gain site reference is assigned to an approved application by the operator software.

2023-01-31 07:45 UTC, teddmason commented
> 

Yes I got muddled with gainsitereference and applicationreference, despite what you say the operator team expect applicationreference to be submitted to them under the name gainsitereference. I'll try and be consistent ourside and only set it to gainsitereference on submission to operator

2023-01-31 07:45 UTC, teddmason commented
> In addition to file specific comments I am wondering if:
> 
> * gain-site-reference needs renaming to application-reference.
> * gainSiteReference needs renaming to applicationReference.
> 
> Based on service level communications I believe
> 
> * an application reference number is associated with journey data submitted for operator validation.
> * a gain site reference is assigned to an approved application by the operator software.

Yes I got muddled with gainsitereference and applicationreference, despite what you say the operator team expect applicationreference to be submitted to them under the name gainsitereference. I'll try and be consistent ourside and only set it to gainsitereference on submission to operator

2023-01-31 12:30 UTC, pwadmore-ea submitted a review, later dismissed

2023-02-10 14:26 UTC, pwadmore-ea approved these changes

2023-02-10 14:26 UTC, merged