feature/BNGP-1796 - Save and return emails
DEFRA/biodiversity-net-gain-service pull request #225
Opened 2023-01-31 18:17 UTC by pwadmore-ea

https://eaflood.atlassian.net/browse/BNGP-1796

2023-02-14 14:31 UTC, teddmason commented on packages/errors-lib/__tests__/unknown-appliication-session-id-error-spec.js
> +import { UnknownApplicationSessionIdError } from '../src/errors.js'
File name spelling error

2023-02-14 14:35 UTC, teddmason requested changes
just one file name spelling error

2023-02-14 17:51 UTC, pwadmore-ea commented on packages/errors-lib/__tests__/unknown-appliication-session-id-error-spec.js
> +import { UnknownApplicationSessionIdError } from '../src/errors.js'
Corrected

2023-02-17 11:19 UTC, teddmason submitted a review, later dismissed

2023-02-22 14:17 UTC, teddmason approved these changes

2023-02-23 08:27 UTC, merged