Feature/bngp 2175 email address correct
DEFRA/biodiversity-net-gain-service pull request #246
Opened 2023-03-14 10:42 UTC by usman-j-shaikh

This PR includes changes about email address confirmation.
- Email address validator
- Confirm email address page for DJ
- Modified helper method

2023-03-16 10:52 UTC, teddmason requested changes

2023-03-16 10:52 UTC, teddmason commented on packages/webapp/src/views/developer/details-email-confirm.html
> +                {% if errorMessage %}
Don't think it needs the if statement here just to set the errorMessage, errorMessage could just be set as an empty object/array if not in error

2023-03-16 10:52 UTC, teddmason commented on packages/webapp/src/views/developer-form-layout.html
How come you need this file? looks to be nearly the same as the current form-layout.html file?

2023-03-16 10:52 UTC, teddmason commented on packages/webapp/src/utils/constants.js
> +const DEVELOPER_CONFIRM_EMAIL = 'developer-yes'
This redis key needs a bit more description probably something like developer-confirm-email, developer-yes doesn't sound right?

2023-03-16 10:58 UTC, usman-j-shaikh commented on packages/webapp/src/views/developer-form-layout.html
We have different page title, and to define this title each and every page not sound good
And I think more changes will come in future which will slightly differ than LOJ
So I want to centralize this work using this file

2023-03-16 14:21 UTC, pwadmore-ea requested changes

2023-03-17 09:37 UTC, pwadmore-ea approved these changes

2023-03-17 09:40 UTC, teddmason approved these changes

2023-03-17 09:40 UTC, merged