Feat/BNGP-1658-upload-agent-authorisation-1
DEFRA/biodiversity-net-gain-service pull request #399
Opened 2023-08-14 18:41 UTC by KiranVarma02

2023-08-22 13:35 UTC, KiranVarma02 commented
duplicate - created new branch

2023-08-25 07:28 UTC, KiranVarma02 commented on packages/webapp/src/routes/land/landowner-permission-upload.js
> +    request.yar.set(constants.redisKeys.LANDOWNER_PERMISSION_UPLOAD_FILE_TYPE, result.fileType)
this

2023-09-13 11:26 UTC, AjinkyaJawalkar requested changes

2023-09-13 11:26 UTC, AjinkyaJawalkar commented on packages/webapp/src/__mock-data__/uploads/written-consent/wrong-extension copy.txt
Remove this duplicate file

2023-09-13 11:26 UTC, AjinkyaJawalkar commented on packages/webapp/src/routes/__tests__/land/landowner-permission-check.spec.js
> +    // it('should redirect to Start page if no data applicant data is available in session', async () => {
Remove commented code

2023-09-13 11:29 UTC, AjinkyaJawalkar commented
Overall PR looks good to me apart from the minor code removal requested.

2023-09-13 22:37 UTC, KiranVarma02 commented on packages/webapp/src/routes/__tests__/land/landowner-permission-check.spec.js
> +    // it('should redirect to Start page if no data applicant data is available in session', async () => {
done

2023-09-14 08:51 UTC, AjinkyaJawalkar approved these changes
PR looks good to me. As discussed earlier we need a approval on the same from lead developer

2023-10-11 00:01 UTC, KiranVarma02 commented
created new branch from master and cherry picked commits from this branch. I will create new PR from new branch

2023-10-11 00:01 UTC, closed without merging