BNGP-3538 content changes
DEFRA/biodiversity-net-gain-service pull request #418
Opened 2023-08-31 15:41 UTC by AjinkyaJawalkar

2023-08-31 23:01 UTC, KiranVarma02 reviewed
LGTM. I am happy to approve if you can show me how to get to credit changes in local.

2023-09-01 08:22 UTC, AjinkyaJawalkar commented
> LGTM. I am happy to approve if you can show me how to get to credit changes in local.

@KiranVarma02 You just need to take the latest branch on your local and run the application. you can directly navigate to the respective pages like _http://localhost:3000/credits-estimation/credits-tier_ and on press of continue you will be on _http://localhost:3000/credits-estimation/credits-cost_

2023-09-04 08:56 UTC, paulsimonandrews requested changes
Just need to update `metric` to `Metric` in the error message

2023-09-04 08:56 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-estimation/credits-tier.js
> +const errorMessage = { text: 'Enter the number of credits from the metric up to 2 decimal places, like 23.75.' }
Update `metric` to `Metric`

2023-09-04 08:56 UTC, paulsimonandrews commented on packages/webapp/src/routes/__tests__/credits-estimation/credits-tier.spec.js
> +      expect(res.result).toContain('Enter the number of credits from the metric up to 2 decimal places, like 23.75.')
Update `metric` to `Metric`

2023-09-04 10:33 UTC, paulsimonandrews approved these changes

2023-09-11 09:21 UTC, shaundefra commented
tested by leena

2023-09-11 09:22 UTC, merged