BNGP-2885- initial commit for terms and conditions
DEFRA/biodiversity-net-gain-service pull request #427
Opened 2023-09-08 13:16 UTC by usman-j-shaikh

2023-09-20 08:37 UTC, paulsimonandrews approved these changes
LGTM

2024-02-20 13:34 UTC, paulsimonandrews requested changes
Please update constant names and content errors as requested in comments

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/utils/credits-purchase-constants.js
> +  CREDITS_TERM_AND_CONDITIONS: '/credits-purchase/credits-terms-and-conditions',
Use `CREDITS_PURCHASE_TERMS_AND_CONDITIONS`

Also the URL should be `/credits-purchase/confirm-terms-conditions`

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/utils/credits-purchase-constants.js
> +  CREDITS_CHECK_YOUR_ANSWERS: '/credits-purchase/credits-check-your-answers'
Use `CREDITS_PURCHASE_CHECK_YOUR_ANSWERS`

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/utils/credits-purchase-constants.js
> +  CREDITS_TERMS_AND_CONDITIONS: 'credits-purchase-consent'
Use `CREDITS_PURCHASE_TERMS_AND_CONDITIONS_CONFIRMED`

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-terms-and-conditions.html
> +                <p class="govuk-body">Our <a href="#">privacy notice </a>sets out how we use the personal data.</p>
Use the same link as we use in the footer to the privacy notice: https://www.gov.uk/government/publications/natural-england-privacy-notices/biodiversity-net-gain-privacy-notice

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-terms-and-conditions.html
> +{% set pageHeading = "Terms and Conditions for the purchase of Statutory Biodiversity Credits" %}
Only `Terms` should be capitalised, the rest should all be lowercase

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-terms-and-conditions.html
> +              <h1 class="govuk-heading-xl">{{ pageHeading }}</h1>
Missing an `<h2>Introduction</h2>` that is in the copydeck

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-terms-and-conditions.html
> +                <h2 class="govuk-heading-m">Anti-money laundering</h2>
Heading should be: Customer due diligence

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-terms-and-conditions.html
> +                <p class="govuk-body">All applications to purchase statutory biodiversity credits are subject to anti-money laundering checks. They can only be purchased by applicants who pass those
Should be: "All applications to purchase statutory biodiversity credits are subject to customer due diligence (anti-money laundering) checks. They can only be purchased by applicants who pass those checks."

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-terms-and-conditions.html
> +                <h2 class="govuk-heading-m">Introduction</h2>
This heading should be at the top, and the paragraph below is a repeat of what is at the top

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-terms-and-conditions.html
> +                      html: "I confirm I have read the terms and conditions."
Should be "I confirm I have read the above, and the full terms and conditions"

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-terms-and-conditions.html
> +{% set serviceName = "Purchase statutory biodiversity credits" %}
Should be: "Buy statutory biodiversity credits"

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-purchase/credits-terms-and-conditions.js
> +          text: 'Check the box to confirm you have read the Ts and Cs',
Should be "Check the box to confirm you have read the terms and conditions"

2024-02-20 13:34 UTC, paulsimonandrews commented on packages/webapp/src/routes/__tests__/credits-purchase/credits-terms-and-conditions.spec.js
> +      expect(res.payload).toContain('Check the box to confirm you have read the Ts and Cs')
Will need to change as content is wrong in the page

2024-02-21 12:38 UTC, paulsimonandrews requested changes
Just need to change the URL for the route (and rename the route and views files accordingly)

2024-02-21 12:38 UTC, paulsimonandrews commented on packages/webapp/src/utils/credits-purchase-constants.js
> +  CREDITS_PURCHASE_TERMS_AND_CONDITIONS: '/credits-purchase/credits-terms-and-conditions',
URL should be: `/credits-purchase/confirm-terms-conditions`

2024-02-21 16:06 UTC, paulsimonandrews approved these changes

2024-02-26 10:09 UTC, paulsimonandrews approved these changes
LGTM

2024-02-26 10:10 UTC, shaundefra commented
Tested by Tajinder

2024-02-26 10:11 UTC, merged