feat: completed need-add-all-planning-authorities
DEFRA/biodiversity-net-gain-service pull request #462
Opened 2023-10-12 21:46 UTC by KiranVarma02

2023-10-18 16:59 UTC, pwadmore-ea requested changes
- I cannot see any reference to the local planning authority picklist referenced from AC1 on the Jira story. The current implementation allows free text entry which does not match the acceptance criteria. I was expecting something like a new database table to hold the picklist and use of that picklist to populate HTML options similar to the prototype (https://github.com/defra-design/biodiversity-net-gain-prototype/blob/main/app/views/register-application/v21/legal-agreement-lpa-add.html)
- Changing a local planning authority appears to add a new item rather than replacing the existing item. Resolution of this issue should be accompanied by additional unit tests.
- Is packages/webapp/src/views/land/legal-party-add-start.html still required or can it be deleted in this pull request or an associated pull request for legal agreement changes?

2023-10-18 20:03 UTC, KiranVarma02 commented
> * does not match the acceptance criteria

1. Next commit will address first issue but need your thoughts/input please
2. Fixed in next commit
3. legal-party-add-start.html is still required because it has different heading and button text

2023-10-18 20:07 UTC, KiranVarma02 commented on packages/webapp/src/routes/__tests__/land/check-planning-authorities.spec.js
> +    it('should show all landowners that are added', async () => {
done

2023-10-18 20:07 UTC, KiranVarma02 commented on packages/webapp/src/routes/__tests__/land/check-planning-authorities.spec.js
> +        payload: { addAnotherplanningAuthority: 'yes' }
done

2023-10-23 12:08 UTC, pwadmore-ea commented
@KiranVarma02  - I have a couple of additional comments:

- Display for a single local planning authority should not include a comma and a question should end with a question mark.
![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/6e72c8bf-6a2d-454e-89d9-c114f1b9ee5a)
- Accessible autocomplete integration for local planning authorities does not cover this error condition on the copydeck:

If text entered doesn’t match what’s in the list
 No match for “[text entered]” – select a local planning authority from the list

Currently, an invalid local planning authority  is accepted.

![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/3c5d206e-016d-4527-8f1b-17ff3ea10500)

2023-10-24 11:46 UTC, pwadmore-ea commented
@shaundefra  - Approving this pull request for merge to the base branch  for legal agreement updates (feat/legal-agreement-base-branch) so that associated functionality can be merged . Preventing the submission of invalid local planning authorities and duplicate local planning authorities will need addressing in subsequent pull requests

2023-10-24 11:47 UTC, pwadmore-ea approved these changes
Approved based on known issues to be resolved in subsequent pull requests.

2023-10-24 11:48 UTC, merged