Feature/BNGP-3443&3169: Enable upload of proof of ownership for multiple landowners
DEFRA/biodiversity-net-gain-service pull request #474
Opened 2023-10-23 14:42 UTC by usman-j-shaikh

2023-11-05 22:43 UTC, paulsimonandrews requested changes
Some comments in the code to address.

Also, the E2E journey is now broken as the other landowners and consent pages have been bypassed but they are still expected in the payload generated on submission. The test data works, but if you manually fill in the journey it won't work. So:
* Remove the other landowner and consent pages and redis cache variables
* Update the payload (`application.js` and `application-validation`) to remove `landownerConsent` and `otherLandowners`
* Remove seed test data for other landowners and consent

There is also a bug: press back link on "land-ownership-list" page and click "Save and continue" again and it will add the file again on the "land-ownership-list" page. Check the code for uploading multiple files in the legal agreement section of the journey as it doesn't do this.

2023-11-05 22:43 UTC, paulsimonandrews commented on packages/webapp/src/routes/land/check-ownership-proof-file.js
> +        path.basename(fileLocation)
The filename is already available in `context` so no need to extract it again

2023-11-05 22:43 UTC, paulsimonandrews commented on packages/webapp/src/routes/land/check-ownership-proof-file.js
> +      _.remove(ownershipProofs, (item) => item === path.basename(context.fileLocation))
Not sure why you are doing this (remove operation followed by setting the redis key) as the file won't have been added to `LAND_OWNERSHIP_PROOFS` at this stage.

Also, even though I don't think you need this line of code, I wouldn't use lodash here, it's an unnecessary dependency for such as simple operation that can be achieved with the built in Array methods (filter or splice with findIndex)

2023-11-07 23:38 UTC, paulsimonandrews requested changes
Two small changes please (see comments in code). Will approve when done.

2023-11-08 09:29 UTC, paulsimonandrews submitted a review, later dismissed

2023-11-17 12:07 UTC, pwadmore-ea requested changes
In additional to other review comments:

-  incorrect copy is displayed when being asked to confirm removal of a document showing proof of land ownership, Save and Continue is pressed and no option has been selected.

![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/f7f74921-93a1-472f-a04d-1031d4152d44)

- If all proof of land ownership files are removed I think the check your answers page should revert to an in progress status and any attempt to navigate to /land/ownership-proof-list with no uploads should redirect to /land/upload-ownership-proof (similar to how the legal agreement section works). At the moment, when the page is viewed in this way it has incorrect pluralisation.

![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/234e4028-66f0-422d-b352-07893c63d248)

- Check and submit page handling for multiple proof of land ownership documents differs from that for multiple legal agreement documents. As I cannot find any guidance in the prototype or copydeck I suggest the approach used for legal agreement documents needs to be followed:

![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/8284e45d-b408-45ee-92f7-ae1c33641612)

![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/be4440c6-7f76-46d8-8124-7466fedeaaa5)

2023-11-24 13:23 UTC, pwadmore-ea requested changes
@AjinkyaJawalkar  - The check and submit page is still showing a link for each proof of ownership upload rather than grouping them with one link (as for legal agreement files - see the screenshot on my previous comment). It works but it's inconsistent and the copydeck screenshots only have an example with one file.

@shaundefra has confirmed a defect will be raised if this is not resolved before pull request approval.

2023-11-24 16:34 UTC, pwadmore-ea approved these changes
> @AjinkyaJawalkar - The check and submit page is still showing a link for each proof of ownership upload rather than grouping them with one link (as for legal agreement files - see the screenshot on my previous comment). It works but it's inconsistent and the copydeck screenshots only have an example with one file.
> 
> @shaundefra has confirmed a defect will be raised if this is not resolved before pull request approval.

@shaundefra  and @paulsimonandrews  - Following agreement that the check and submit inconsistency will be treated as a known issue so the next deployment is not delayed I will  approve the pull request.,

2023-11-28 11:11 UTC, LeenaKu commented
Tested on POC3 and known issues covered by https://eaflood.atlassian.net/browse/BNGP-3443?focusedCommentId=554208.

2023-11-28 11:11 UTC, merged