BNGP-3901: Database script updates for 3901
DEFRA/biodiversity-net-gain-service pull request #529
Opened 2023-12-01 11:10 UTC by teddmason

2023-12-08 16:21 UTC, pwadmore-ea requested changes

2023-12-11 08:20 UTC, teddmason commented on packages/webapp/src/utils/get-application.js
> +    return h.redirect(constants.routes.CANNOT_VIEW_APPLICATION)
Ticket created: https://eaflood.atlassian.net/browse/BNGP-4173

2023-12-11 08:20 UTC, teddmason commented on packages/webapp/src/utils/get-application.js
> +    return h.redirect(`${constants.routes.CANNOT_VIEW_APPLICATION}?orgError=true`)
https://eaflood.atlassian.net/browse/BNGP-4173

2023-12-12 08:58 UTC, pwadmore-ea submitted a review, later dismissed

2023-12-14 14:38 UTC, pwadmore-ea approved these changes

2023-12-15 08:34 UTC, shaundefra commented
tested locally

2023-12-15 08:34 UTC, merged