BNGP-3150: Main Credits Journey: Credits Reference Number Generation
DEFRA/biodiversity-net-gain-service pull request #531
Opened 2023-12-04 12:24 UTC by usman-j-shaikh

2024-02-21 23:13 UTC, paulsimonandrews requested changes
Done a quick review and require some changes. Once the database migrations are sorted I will test behaviour of the code

2024-02-21 23:13 UTC, paulsimonandrews commented on packages/webapp/src/routes/test/seed-credits-estimation-data.js
use credits-purchase not credits-estimation in filename and throughout this file

2024-02-21 23:13 UTC, paulsimonandrews commented on packages/webapp/src/utils/constants.js
> +const TEST_CREDITS_ESTIMATION_DATA = 'test/seed-credits-estimation-data'
CREDITS_PURCHASE not ESTIMATION

2024-02-21 23:13 UTC, paulsimonandrews commented on packages/webapp/src/utils/credits-application.js
> +        firstName: account.idTokenClaims.firstName,
Won't need firstName, lastName and emailAddress in the payload so can remove them. We only need the contactId

2024-02-21 23:13 UTC, paulsimonandrews commented on packages/webapp/src/views/test/seed-credits-estimation-data.html
should be credits-purchase not credits-estimation

2024-02-21 23:13 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-confirmation.html
> +    <p>We will send you a confirmation email.</p>
Doesn't match latest copydeck. Should be `We have sent you a confirmation email.`

2024-02-21 23:13 UTC, paulsimonandrews commented on packages/webapp/src/utils/credits-application-validation.js
> +      firstName: Joi.string().required(),
Won't need firstName, lastName and emailAddress (see comment below)

2024-02-22 08:16 UTC, paulsimonandrews commented on packages/database-version-control/src/migrations/2023.12.01T11.49.55.create-credits-app-reference-function.sql
Rename this migration so it occurs after the 2024.02.15 migration that adds the `CreditsPurchase` type

2024-02-28 13:28 UTC, paulsimonandrews approved these changes

2024-02-28 13:47 UTC, shaundefra commented
Tested locally

2024-02-28 13:47 UTC, merged