BNGP-4124: Multiple landownership upload: allows empty strings on removal
DEFRA/biodiversity-net-gain-service pull request #538
Opened 2023-12-08 14:14 UTC by usman-j-shaikh

2023-12-11 14:14 UTC, teddmason approved these changes

2023-12-19 09:46 UTC, teddmason requested changes

2023-12-19 09:46 UTC, teddmason commented on packages/webapp/src/utils/__tests__/test-helpers.spec.js
> +  it.only('should revert completed status to in progress based on flag', () => {
it.only has been left in

2023-12-19 09:47 UTC, teddmason commented on packages/webapp/src/utils/__tests__/test-helpers.spec.js
> +  it.only('should revert completed status to in progress based on flag', () => {
please can you update base too, there is an option on the pr to merge master in

2023-12-19 11:35 UTC, teddmason approved these changes

2023-12-20 14:57 UTC, shaundefra commented
tested by leena

2023-12-20 14:58 UTC, merged