feat: BNGP-3912 Change Applicant info from CYA
DEFRA/biodiversity-net-gain-service pull request #550
Opened 2023-12-19 11:49 UTC by KiranVarma02

2023-12-22 14:12 UTC, pwadmore-ea requested changes
In addition to my comments on individual files:

- If the user confirms they want to change applicant information it is possible for them to go back to the dashboard, work on another application before the replacement applicant information is complete. When the user returns to the application with partially modified applicant information, null and undefined data is shown on the check your answers page. For example:
![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/a00e6b72-6529-4215-ac5f-30308fdbc4ec)
- I don't think changing if applicant is an individual or organisation is compatible with https://github.com/DEFRA/biodiversity-net-gain-service/pull/529. Since the application dashboard is now filtered according to how the user logged in I don't believe it is possible to change whether the user is representing themselves or an organisation on a particular application. This provides rationale for reconsidering this area of functionality.

2024-01-02 10:59 UTC, KiranVarma02 commented on packages/webapp/src/routes/__tests__/land/change-client-individual-organisation.spec.js
> +    it('Should continue journey to CHECK_APPLICANT_INFORMATION if user does not want to change applying as individual or organisation', async () => {
What is wrong here?

2024-01-02 11:02 UTC, KiranVarma02 commented on packages/webapp/src/routes/land/change-applying-individual-organisation.js
> +      request.yar.clear(constants.redisKeys.CLIENT_INDIVIDUAL_ORGANISATION_KEY)
IS_AGENT is to clear behalf of a client, CLIENT_INDIVIDUAL_ORGANISATION_KEY is to clear individual or org. Seems okay to me. Please check again.

2024-01-02 11:03 UTC, KiranVarma02 commented on packages/webapp/src/routes/land/change-applying-individual-organisation.js
> +      request.yar.clear(constants.redisKeys.CLIENTS_PHONE_NUMBER_KEY)
is this a duplicate comment? please check again.

2024-01-08 10:56 UTC, pwadmore-ea requested changes
@KiranVarma02  - I've resolved some review comments following your comments and hope I've clarified the others.

2024-01-08 10:56 UTC, pwadmore-ea commented on packages/webapp/src/routes/__tests__/land/change-client-individual-organisation.spec.js
> +    it('Should continue journey to CLIENT_INDIVIDUAL_ORGANISATION if user confirms to changing legal agreement', async () => {
This pull request has nothing to do with legal agreements so the text in bold needs correcting.

2024-01-08 10:56 UTC, pwadmore-ea commented on packages/webapp/src/routes/__tests__/land/change-client-individual-organisation.spec.js
> +    it('Should continue journey to CHECK_APPLICANT_INFORMATION if user does not want to change applying as individual or organisation', async () => {
As the tests file in this file appear to be for an agent acting on behalf of an individual or organisation I suggested adding the text in bold.

2024-01-08 10:56 UTC, pwadmore-ea commented on packages/webapp/src/routes/land/change-applying-individual-organisation.js
> +      request.yar.clear(constants.redisKeys.CLIENT_INDIVIDUAL_ORGANISATION_KEY)
Thanks. I understand why the CLIENT_ keys are being cleared now.

2024-01-08 10:56 UTC, pwadmore-ea commented on packages/webapp/src/routes/land/change-applying-individual-organisation.js
> +      request.yar.clear(constants.redisKeys.CLIENTS_PHONE_NUMBER_KEY)
This comment is linked to the highlighted keys but I understand why they are being cleared now.

2024-01-08 13:28 UTC, KiranVarma02 commented on packages/webapp/src/routes/__tests__/land/change-client-individual-organisation.spec.js
> +    it('Should continue journey to CHECK_APPLICANT_INFORMATION if user does not want to change applying as individual or organisation', async () => {
done

2024-01-08 13:29 UTC, KiranVarma02 commented on packages/webapp/src/routes/__tests__/land/change-applying-individual-organisation.spec.js
> +    it('Should continue journey to APPLICATION_BY_INDIVIDUAL_OR_ORGANISATION if user confirms to changing legal agreement', async () => {
done

2024-01-17 11:44 UTC, pwadmore-ea commented on packages/webapp/src/routes/__tests__/land/change-applying-individual-organisation.spec.js
> +    it('Should continue journey to APPLICATION_BY_INDIVIDUAL_OR_ORGANISATION if user confirms to changing legal agreement', async () => {
@KiranVarma02  - **legal agreement** is the typo that needs changing as this is not a legal agreement story.

2024-01-17 11:57 UTC, KiranVarma02 commented on packages/webapp/src/routes/__tests__/land/change-applying-individual-organisation.spec.js
> +    it('Should continue journey to APPLICATION_BY_INDIVIDUAL_OR_ORGANISATION if user confirms to changing legal agreement', async () => {
this says outdated, it was corrected when you put first comment. Do you not see update? not sure whats happening!

2024-01-17 12:33 UTC, pwadmore-ea commented on packages/webapp/src/routes/__tests__/land/change-applying-individual-organisation.spec.js
> +    it('Should continue journey to APPLICATION_BY_INDIVIDUAL_OR_ORGANISATION if user confirms to changing legal agreement', async () => {
As discussed I commented on the wrong file earlier and will resolve this conversation.

2024-01-17 12:49 UTC, pwadmore-ea approved these changes

2024-01-24 20:43 UTC, shaundefra commented
tested by @LeenaKu

2024-01-24 20:43 UTC, merged