BNGP-4307: Create a Service down/Shutter static HTML page
DEFRA/biodiversity-net-gain-service pull request #560
Opened 2023-12-29 11:22 UTC by usman-j-shaikh

2024-01-02 23:18 UTC, paulsimonandrews requested changes
The shutter page should be a static HTML page, not a nunjucks templated page. 

It's a standalone page that isn't served by the web app but loaded into the cloud firewall when the web app is unreachable.

Please follow the instructions on the JIRA ticket

2024-01-02 23:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/__tests__/shutter-page.spec.js
Remove this file, it's not needed. The shutter page isn't served by the web app.

2024-01-02 23:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/shutter-page.js
Remove this file, it's not needed. The shutter page isn't served by the web app.

2024-01-02 23:18 UTC, paulsimonandrews commented on packages/webapp/src/utils/constants.js
Remove these edits from constants, they are not needed. The shutter page isn't served by the web app.

2024-01-02 23:18 UTC, paulsimonandrews commented on packages/webapp/src/views/shutter-page.html
The shutter page isn't a nunjucks templated page but a standalone static HTML page

2024-01-04 15:35 UTC, KiranVarma02 reviewed
should file name be down.html like example for some reason as example in ticket, or is it not necessary?

2024-01-05 09:40 UTC, KiranVarma02 approved these changes

2024-01-08 13:32 UTC, KiranVarma02 approved these changes

2024-01-10 12:23 UTC, LeenaKu commented
Tested and Passed

2024-01-10 18:05 UTC, KiranVarma02 approved these changes

2024-01-11 14:30 UTC, AjinkyaJawalkar approved these changes

2024-01-16 14:50 UTC, paulsimonandrews approved these changes

2024-01-16 15:04 UTC, merged