feature/BNGP-4369-ITHC-csp-fix
DEFRA/biodiversity-net-gain-service pull request #579
Opened 2024-01-15 00:48 UTC by soorajvdefra

2024-01-16 13:14 UTC, pwadmore-ea requested changes
In addition to my comments on individual files I recommend adding some unit tests to check the content security policy header is being set correctly. For example, https://github.com/DEFRA/wildlife-licencing/blob/29a748ef8d15c1fe7981ea8da3ad570c1987a1d0/packages/web-service/src/__tests__/additional-page-data.spec.js

2024-01-16 13:37 UTC, soorajvdefra commented on packages/webapp/src/server.js
> +                        `script-src 'self' 'nonce-${nonce}' 'sha256-${scriptHash}'; ` +
hi @pwadmore-ea i have used nonce only 'sha256 also required to fix the internal inline script of govuk/template.njk
reference 
https://github.com/alphagov/govuk-frontend/issues/1657
https://technology.blog.gov.uk/2015/02/12/experimenting-with-content-security-policy-on-gov-uk/

2024-01-17 14:00 UTC, soorajvdefra commented on packages/webapp/src/server.js
> +                        `script-src 'self' 'nonce-${nonce}' 'sha256-${scriptHash}'; ` +
comment and gtm  added

2024-01-17 14:01 UTC, soorajvdefra commented on packages/webapp/src/server.js
> +      if (typeof response.header === 'function') {
this code removed as its not required

2024-01-17 14:15 UTC, pwadmore-ea approved these changes

2024-01-22 09:09 UTC, shaundefra commented
tested locally

2024-01-22 09:09 UTC, merged