BNGP-4419: Check and submit : multiple Landownership uploads create a new row instead of one and a list of upload
DEFRA/biodiversity-net-gain-service pull request #587
Opened 2024-01-17 14:39 UTC by usman-j-shaikh

2024-01-22 21:20 UTC, paulsimonandrews requested changes
Tiny change to remove commented out code.

2024-01-22 21:20 UTC, paulsimonandrews commented on packages/webapp/src/routes/land/check-and-submit.js
> +    // landownershipFileNames: getFileNameByType(applicationDetails.files, 'land-ownership'),
Remove comment

2024-01-23 13:49 UTC, paulsimonandrews approved these changes
LGTM

2024-01-23 15:36 UTC, shaundefra commented
tested by Tajinder

2024-01-23 15:36 UTC, merged