BNGP-3953: Update 'Check and submit' page to reflect v21 of the prototype
DEFRA/biodiversity-net-gain-service pull request #594
Opened 2024-01-19 14:29 UTC by usman-j-shaikh

2024-01-22 12:42 UTC, paulsimonandrews requested changes
Changes don't fully match prototype/copydeck

2024-01-22 12:42 UTC, paulsimonandrews commented on packages/webapp/client/sass/application.scss
> +$govuk-font-family: "GDS Transport", arial, sans-serif !important;
Remove "GDS Transport", we can't use it for licensing reasons. Correct font throughout should be arial

2024-01-22 12:42 UTC, paulsimonandrews commented on packages/webapp/src/views/land/check-and-submit.html
> +      <h2 class="govuk-heading-m">Land boundary</h2>
Wording doesn't match the copy deck

2024-01-22 12:42 UTC, paulsimonandrews commented on packages/webapp/src/views/land/check-and-submit.html
> +      <h2 class="govuk-heading-m">Land ownership</h2>
Doesn't match copy deck. This section should come after applicant information

2024-01-22 12:42 UTC, paulsimonandrews commented on packages/webapp/src/views/land/check-and-submit.html
> +              text: "Land boundary file uploaded"
Wording doesn't match copy deck

2024-01-22 18:08 UTC, pwadmore-ea requested changes
![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/bc6fe5b1-7143-4373-9102-5ceafcf84bdb)

- This does not reflect the copydeck/other uploads types . Other upload types group multiple files in a single row such as.

![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/48295052-54f9-4d25-95b5-774c46d051b6)

- If other landholders or leaseholders are present they should be output. This does not match the copydeck:

![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/0d7b2477-0e81-4e94-954b-d2829cdbd90e)

Compare with copydeck:
![image](https://github.com/DEFRA/biodiversity-net-gain-service/assets/8915039/58400d5f-decf-4d06-83ee-d9ad9747c149)

2024-01-23 06:59 UTC, usman-j-shaikh commented
> ![image](https://private-user-images.githubusercontent.com/8915039/298677474-bc6fe5b1-7143-4373-9102-5ceafcf84bdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTMyMzIsIm5iZiI6MTcwNTk5MjkzMiwicGF0aCI6Ii84OTE1MDM5LzI5ODY3NzQ3NC1iYzZmZTViMS03MTQzLTQzNzMtOTEwMi01Y2VhZmNmODRiZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDY1NTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWU2OWNjZDFhOGRlODg1NzI2YTMwZTlmYzA4MmZiMjIyNWIzYzZlMjZmY2Y3ZjVhYzJlN2E3YjRmNmYyYjAzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dA53wIeRq4CiGFSNq1cyHWc0uoqLnQLqxQ40uIkssgc)
> 
> * This does not reflect the copydeck/other uploads types . Other upload types group multiple files in a single row such as.
> 
> ![image](https://private-user-images.githubusercontent.com/8915039/298678536-48295052-54f9-4d25-95b5-774c46d051b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTMyMzIsIm5iZiI6MTcwNTk5MjkzMiwicGF0aCI6Ii84OTE1MDM5LzI5ODY3ODUzNi00ODI5NTA1Mi01NGY5LTRkMjUtOTViNS03NzRjNDZkMDUxYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDY1NTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjU1N2EyNTJhYjA5N2Q1NmVmZDY3NDY2Y2UwYTliZGI5ZGE2YzVkNWU1MDU4MTMwZDJiMDU1MWUxNjM4MDAzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oYzG6h_8Go73Aj-mstUc7s4hCjghKYzQ3f_NbKElcJw)
> 
> * If other landholders or leaseholders are present they should be output. This does not match the copydeck:
> 
> ![image](https://private-user-images.githubusercontent.com/8915039/298679886-0d7b2477-0e81-4e94-954b-d2829cdbd90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTMyMzIsIm5iZiI6MTcwNTk5MjkzMiwicGF0aCI6Ii84OTE1MDM5LzI5ODY3OTg4Ni0wZDdiMjQ3Ny0wZTgxLTRlOTQtOTU0Yi1kMjgyOWNkYmQ5MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDY1NTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkyNzYyYTk5NDBjMzQ5MGE5ZGQ2NjlkMjMyNDIxZjI0YWZmNTU1M2I1YzkxZTExODFiOWFhMmIzMDNiMjcxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.je-f1ST48UzO2x2cdxbd7ZmLs05g2YD5KID0MuE74zs)
> 
> Compare with copydeck: ![image](https://private-user-images.githubusercontent.com/8915039/298679347-58400d5f-decf-4d06-83ee-d9ad9747c149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTMyMzIsIm5iZiI6MTcwNTk5MjkzMiwicGF0aCI6Ii84OTE1MDM5LzI5ODY3OTM0Ny01ODQwMGQ1Zi1kZWNmLTRkMDYtODNlZS1kOWFkOTc0N2MxNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDY1NTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY2Mzg1Y2ZjNGUxMTY5NjM4ZWY5NWM5OWE0OGMzMWM2ZjhmZWY3Y2RkMjY4NzVjMjc5MWNmN2JlNGM3YzYxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vZ6Dp9P85vEeI_cCXFrqvIVDwgs3jo5hOklcwj-AqEA)

@pwadmore-ea 
Land Ownership issue already covered in https://github.com/DEFRA/biodiversity-net-gain-service/pull/587

2024-01-24 13:30 UTC, pwadmore-ea approved these changes

2024-01-24 21:00 UTC, paulsimonandrews approved these changes

2024-01-26 16:04 UTC, shaundefra commented
tested locally

2024-01-26 16:04 UTC, merged