BNGP-4472: Update Dashboard "Manage Biodiversity Gains" page to include the credits service option
DEFRA/biodiversity-net-gain-service pull request #608
Opened 2024-01-31 12:31 UTC by usman-j-shaikh

2024-02-23 16:34 UTC, paulsimonandrews requested changes
Couple of minor changes to get it working correctly

2024-02-23 16:34 UTC, paulsimonandrews commented on packages/webapp/src/utils/constants.js
> +const CREDITS_PURCHASE = 'credits-purchase'
Change to `CreditsPurchase` as that is what the type is called in the database.

2024-02-23 16:34 UTC, paulsimonandrews commented on packages/webapp/src/routes/manage-biodiversity-gains.js
> +      enableCredits: process.env.ENABLE_ROUTE_SUPPORT_FOR_CREDIT_ESTIMATION_JOURNEY === 'Y',
Should be `ENABLE_ROUTE_SUPPORT_FOR_CREDIT_PURCHASE_JOURNEY`

2024-02-27 14:08 UTC, paulsimonandrews approved these changes
LGTM

2024-02-27 14:48 UTC, shaundefra commented
tested locally

2024-02-27 14:49 UTC, merged