BNGP-2880: Main Credits Journey: Individual or Organisation
DEFRA/biodiversity-net-gain-service pull request #615
Opened 2024-02-05 17:03 UTC by usman-j-shaikh

2024-02-14 12:28 UTC, pwadmore-ea requested changes
Use of constants.landownerTypes needs to be replaced with use of costants.individualOrOrganisationTypes following he merge of https://github.com/DEFRA/biodiversity-net-gain-service/pull/515 to master.

2024-02-16 15:32 UTC, pwadmore-ea reviewed
I'm happy with the changes made so far.

Approval relies on alignment with the copydeck (URLs should be finalised but error messages are still to be confirmed).

2024-02-23 16:18 UTC, paulsimonandrews requested changes
Just content changes to match the latest versions of the copydecks.

Please update and rename routes, views and test files to follow the latest URLs

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-purchase/credits-metric-upload.js
> +          text: 'Select a Biodiversity Metric',
Error message should be `Upload the statutory biodiversity metric file with the ‘unit shortfall summary’ tab` to match the copydeck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-metric-upload-check.html
This should be `/credits-purchase/check-metric-file` to match the copy deck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-metric-upload-check.html
> +        {% set checkUploadCorrectYesText = 'Yes, this is the Secretary of State Metric file my local planning authority reviewed' %}
Should be `Yes, this is the statutory biodiversity metric file my local planning authority reviewed` to match the copy deck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-purchase/credits-metric-upload-check.js
> +          text: 'Select yes if this is the correct file',
Should be `Select yes if this is the statutory biodiversity metric file your local planning authority reviewed with your biodiversity net gain statement` to match the copy deck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-purchase/credits-development-location.js
Should be `credits-purchase/confirm-development-details` to match the copy deck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-development-location.html
Should be `credits-purchase/confirm-development-details` to match the copy deck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/credits-development-location.html
> +      <p>These details have been taken from the Secretary of State Metric file your local planning authority reviewed.</p>
Should be `These details have been taken from the statutory biodiversity metric calculation tool your local planning authority reviewed.` to match the copy deck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-purchase/credits-development-location.js
> +            text: 'Select yes if this is the correct file',
Should be `Select yes if these details are correct` to match the copy deck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-purchase/applying-individual-organisation.js
Should be `/credits-purchase/purchasing-individual-organisation` to match the copydeck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/views/credits-purchase/applying-individual-organisation.html
Should be `/credits-purchase/purchasing-individual-organisation` to match the copydeck

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-purchase/applying-individual-organisation.js
> +const organisationSignInErrorMessage = 'Select \'organisation\' if you are purchasing statutory biodiversity credits as an organisation'
These are the current messages in the latest version of the copydecks so I suggest we leave them and ask design to review the build for changes. We shouldn't be making these decisions!

2024-02-23 16:18 UTC, paulsimonandrews commented on packages/webapp/src/routes/credits-purchase/applying-individual-organisation.js
> +const organisationSignInErrorMessage = 'Select \'organisation\' if you are purchasing statutory biodiversity credits as an organisation'
So I suggest leave these as they are for now.

2024-03-01 00:07 UTC, paulsimonandrews approved these changes

2024-03-04 15:43 UTC, shaundefra commented
tested locally

2024-03-04 15:43 UTC, merged