BNGP:5403 Add metric rows to habitat matching displays
DEFRA/biodiversity-net-gain-service pull request #848
Opened 2024-09-04 11:40 UTC by thousand-leaves

https://eaflood.atlassian.net/browse/BNGP-5403

This change adds the metric row numbers to the /combined-case/match-habitats and the habitat matching cya page /combined-case/match-allocation-summary.

2024-09-16 19:39 UTC, paulsimonandrews requested changes
Couple of minimal changes to adjust formatting

2024-09-16 19:39 UTC, paulsimonandrews commented on packages/webapp/src/views/combined-case/match-allocation-summary.html
> +            <div class="govuk-grid-column-full">
Can we switch this to `three-quarters` instead of `full`

2024-09-16 19:39 UTC, paulsimonandrews commented on packages/webapp/src/routes/combined-case/match-allocation-summary.js
> +        value: matchedHabitat ? `${matchedHabitat.size} ${matchedHabitat.measurementUnits} / ${matchedHabitat.condition} Condition / Row ${matchedHabitat.rowNum}` : '',
Put a `&nbsp;` between `Row` and its number to make the formatting a bit nicer

2024-09-18 11:15 UTC, paulsimonandrews approved these changes
LGTM

2024-09-25 11:01 UTC, shaundefra commented
tested locally

2024-09-25 11:02 UTC, merged